### ISSUE TITLE
Implement Comparison Rule For Checking If Source Is Contained In Target

### ISSUE THREAD

**Issue by mlaguren** [Cell-Checker/cell-checker#21]
**Is your feature request related to a problem? Please describe.**
In order to support an internal EcoATM project,
I would like a comparison rule that utilizes pandas .isin function,
So that I validate if every in the source is in the target frame

**Describe the solution you'd like**
I would like to have Cell Checker validate that every row in the source is in the target by writing the following test case:

```
test:
  name: "Source Is In Target"
  source:
    type: "csv"
    location: "./data_validation_tests/small_source.csv"
  target:
    type: "csv"
    location: "./data_validation_tests/large_target.csv"
  comparison_rules:
    - contains_source
```

Utilizing pandas .isin function, I should be able to determine that with some additional logic, since .isin returns true for every element instead of a single true or false for the entier dataframe.

**Describe alternatives you've considered**
None at this time.

**Additional context**
The .all function will assess whether the entire dataframe is true or not
